root = "."
tmp_dir = "tmp"
[build]
cmd = "sqlc generate && go build -o ./tmp/main ."
bin = "./tmp/main"
delay = 1000                                                         # ms
exclude_dir = ["assets", "tmp", "vendor", "generated", "migrations"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = ["_test\\.go"]
