import "reflect-metadata";
import type { Metadata } from "next";
import "@/app/globals.css";
import { redirect } from "next/navigation";
import Nav from "../components/Nav";
import { getAuthUser } from "@/lib/auth";
import GenericNotification from "@/app/components/GenericNotification";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { loginUrl, user } = await getAuthUser();
  if (!user) return redirect(loginUrl);
  return (
    <html lang="en" data-theme="light">
      <body>
        <Nav />
        <main className="max-w-xl mx-auto">{children}</main>
        <GenericNotification />
      </body>
    </html>
  );
}
